/*
 * Binance Staking REST API
 *
 * OpenAPI Specification for the Binance Staking REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::staking::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSoftStakingRewardsHistoryResponseRowsInner {
    #[serde(rename = "asset", skip_serializing_if = "Option::is_none")]
    pub asset: Option<String>,
    #[serde(rename = "rewards", skip_serializing_if = "Option::is_none")]
    pub rewards: Option<String>,
    #[serde(rename = "rewardAsset", skip_serializing_if = "Option::is_none")]
    pub reward_asset: Option<String>,
    #[serde(rename = "avgAmount", skip_serializing_if = "Option::is_none")]
    pub avg_amount: Option<String>,
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<i64>,
}

impl GetSoftStakingRewardsHistoryResponseRowsInner {
    #[must_use]
    pub fn new() -> GetSoftStakingRewardsHistoryResponseRowsInner {
        GetSoftStakingRewardsHistoryResponseRowsInner {
            asset: None,
            rewards: None,
            reward_asset: None,
            avg_amount: None,
            time: None,
        }
    }
}
