/*
 * Binance Spot WebSocket API
 *
 * OpenAPI Specifications for the Binance Spot WebSocket API
 *
 * API documents:
 * - [Github web-socket-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-api.md)
 * - [General API information for web-socket-api on website](https://developers.binance.com/docs/binance-spot-api-docs/web-socket-api/general-api-information)
 *
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::spot::websocket_api::models;
use serde::{Deserialize, Deserializer, Serialize, de::Error};
use serde_json::Value;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PercentPriceBySideFilter {
    #[serde(rename = "filterType", skip_serializing_if = "Option::is_none")]
    pub filter_type: Option<String>,
    #[serde(rename = "multiplierExponent", skip_serializing_if = "Option::is_none")]
    pub multiplier_exponent: Option<i32>,
    #[serde(rename = "bidMultiplierUp", skip_serializing_if = "Option::is_none")]
    pub bid_multiplier_up: Option<String>,
    #[serde(rename = "bidMultiplierDown", skip_serializing_if = "Option::is_none")]
    pub bid_multiplier_down: Option<String>,
    #[serde(rename = "askMultiplierUp", skip_serializing_if = "Option::is_none")]
    pub ask_multiplier_up: Option<String>,
    #[serde(rename = "askMultiplierDown", skip_serializing_if = "Option::is_none")]
    pub ask_multiplier_down: Option<String>,
    #[serde(rename = "avgPriceMins", skip_serializing_if = "Option::is_none")]
    pub avg_price_mins: Option<i32>,
}

impl PercentPriceBySideFilter {
    #[must_use]
    pub fn new() -> PercentPriceBySideFilter {
        PercentPriceBySideFilter {
            filter_type: None,
            multiplier_exponent: None,
            bid_multiplier_up: None,
            bid_multiplier_down: None,
            ask_multiplier_up: None,
            ask_multiplier_down: None,
            avg_price_mins: None,
        }
    }
}
