/*
 * Binance Simple Earn REST API
 *
 * OpenAPI Specification for the Binance Simple Earn REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::simple_earn::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetRwusdQuotaDetailsResponseStandardRedemptionQuota {
    #[serde(rename = "leftQuota", skip_serializing_if = "Option::is_none")]
    pub left_quota: Option<String>,
    #[serde(rename = "minimum", skip_serializing_if = "Option::is_none")]
    pub minimum: Option<String>,
    #[serde(rename = "fee", skip_serializing_if = "Option::is_none")]
    pub fee: Option<String>,
    #[serde(rename = "redeemPeriod", skip_serializing_if = "Option::is_none")]
    pub redeem_period: Option<i64>,
}

impl GetRwusdQuotaDetailsResponseStandardRedemptionQuota {
    #[must_use]
    pub fn new() -> GetRwusdQuotaDetailsResponseStandardRedemptionQuota {
        GetRwusdQuotaDetailsResponseStandardRedemptionQuota {
            left_quota: None,
            minimum: None,
            fee: None,
            redeem_period: None,
        }
    }
}
