/*
 * Binance Simple Earn REST API
 *
 * OpenAPI Specification for the Binance Simple Earn REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::simple_earn::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetRwusdSubscriptionHistoryResponseRowsInner {
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<i64>,
    #[serde(rename = "asset", skip_serializing_if = "Option::is_none")]
    pub asset: Option<String>,
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<String>,
    #[serde(rename = "receiveAsset", skip_serializing_if = "Option::is_none")]
    pub receive_asset: Option<String>,
    #[serde(rename = "receiveAmount", skip_serializing_if = "Option::is_none")]
    pub receive_amount: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}

impl GetRwusdSubscriptionHistoryResponseRowsInner {
    #[must_use]
    pub fn new() -> GetRwusdSubscriptionHistoryResponseRowsInner {
        GetRwusdSubscriptionHistoryResponseRowsInner {
            time: None,
            asset: None,
            amount: None,
            receive_asset: None,
            receive_amount: None,
            status: None,
        }
    }
}
