/*
 * Binance Simple Earn REST API
 *
 * OpenAPI Specification for the Binance Simple Earn REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::simple_earn::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetRwusdQuotaDetailsResponse {
    #[serde(rename = "subscriptionQuota", skip_serializing_if = "Option::is_none")]
    pub subscription_quota: Option<Box<models::GetRwusdQuotaDetailsResponseSubscriptionQuota>>,
    #[serde(
        rename = "fastRedemptionQuota",
        skip_serializing_if = "Option::is_none"
    )]
    pub fast_redemption_quota: Option<Box<models::GetRwusdQuotaDetailsResponseFastRedemptionQuota>>,
    #[serde(
        rename = "standardRedemptionQuota",
        skip_serializing_if = "Option::is_none"
    )]
    pub standard_redemption_quota:
        Option<Box<models::GetRwusdQuotaDetailsResponseStandardRedemptionQuota>>,
    #[serde(rename = "subscribeEnable", skip_serializing_if = "Option::is_none")]
    pub subscribe_enable: Option<bool>,
    #[serde(rename = "redeemEnable", skip_serializing_if = "Option::is_none")]
    pub redeem_enable: Option<bool>,
}

impl GetRwusdQuotaDetailsResponse {
    #[must_use]
    pub fn new() -> GetRwusdQuotaDetailsResponse {
        GetRwusdQuotaDetailsResponse {
            subscription_quota: None,
            fast_redemption_quota: None,
            standard_redemption_quota: None,
            subscribe_enable: None,
            redeem_enable: None,
        }
    }
}
