/*
 * Binance Simple Earn REST API
 *
 * OpenAPI Specification for the Binance Simple Earn REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::simple_earn::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetRwusdRewardsHistoryResponseRowsInner {
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<i64>,
    #[serde(rename = "rewardsAmount", skip_serializing_if = "Option::is_none")]
    pub rewards_amount: Option<String>,
    #[serde(rename = "rwusdPosition", skip_serializing_if = "Option::is_none")]
    pub rwusd_position: Option<String>,
    #[serde(
        rename = "annualPercentageRate",
        skip_serializing_if = "Option::is_none"
    )]
    pub annual_percentage_rate: Option<String>,
}

impl GetRwusdRewardsHistoryResponseRowsInner {
    #[must_use]
    pub fn new() -> GetRwusdRewardsHistoryResponseRowsInner {
        GetRwusdRewardsHistoryResponseRowsInner {
            time: None,
            rewards_amount: None,
            rwusd_position: None,
            annual_percentage_rate: None,
        }
    }
}
