/*
 * Binance Spot REST API
 *
 * OpenAPI Specifications for the Binance Spot REST API
 *
 * API documents:
 * - [Github rest-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md)
 * - [General API information for rest-api on website](https://developers.binance.com/docs/binance-spot-api-docs/rest-api/general-api-information)
 *
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::spot::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExchangeMaxNumAlgoOrdersFilter {
    #[serde(rename = "filterType", skip_serializing_if = "Option::is_none")]
    pub filter_type: Option<String>,
    #[serde(rename = "maxNumAlgoOrders", skip_serializing_if = "Option::is_none")]
    pub max_num_algo_orders: Option<i64>,
}

impl ExchangeMaxNumAlgoOrdersFilter {
    #[must_use]
    pub fn new() -> ExchangeMaxNumAlgoOrdersFilter {
        ExchangeMaxNumAlgoOrdersFilter {
            filter_type: None,
            max_num_algo_orders: None,
        }
    }
}
