/*
 * Binance Spot REST API
 *
 * OpenAPI Specifications for the Binance Spot REST API
 *
 * API documents:
 * - [Github rest-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md)
 * - [General API information for rest-api on website](https://developers.binance.com/docs/binance-spot-api-docs/rest-api/general-api-information)
 *
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::spot::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "filterType")]
pub enum SymbolFilters {
    #[serde(rename = "PRICE_FILTER")]
    PriceFilter(Box<models::PriceFilter>),
    #[serde(rename = "PERCENT_PRICE")]
    PercentPrice(Box<models::PercentPriceFilter>),
    #[serde(rename = "PERCENT_PRICE_BY_SIDE")]
    PercentPriceBySide(Box<models::PercentPriceBySideFilter>),
    #[serde(rename = "LOT_SIZE")]
    LotSize(Box<models::LotSizeFilter>),
    #[serde(rename = "MIN_NOTIONAL")]
    MinNotional(Box<models::MinNotionalFilter>),
    #[serde(rename = "NOTIONAL")]
    Notional(Box<models::NotionalFilter>),
    #[serde(rename = "ICEBERG_PARTS")]
    IcebergParts(Box<models::IcebergPartsFilter>),
    #[serde(rename = "MARKET_LOT_SIZE")]
    MarketLotSize(Box<models::MarketLotSizeFilter>),
    #[serde(rename = "MAX_NUM_ORDERS")]
    MaxNumOrders(Box<models::MaxNumOrdersFilter>),
    #[serde(rename = "MAX_NUM_ALGO_ORDERS")]
    MaxNumAlgoOrders(Box<models::MaxNumAlgoOrdersFilter>),
    #[serde(rename = "MAX_NUM_ICEBERG_ORDERS")]
    MaxNumIcebergOrders(Box<models::MaxNumIcebergOrdersFilter>),
    #[serde(rename = "MAX_POSITION")]
    MaxPosition(Box<models::MaxPositionFilter>),
    #[serde(rename = "TRAILING_DELTA")]
    TrailingDelta(Box<models::TrailingDeltaFilter>),
    #[serde(rename = "T_PLUS_SELL")]
    TPlusSell(Box<models::TPlusSellFilter>),
    #[serde(rename = "MAX_NUM_ORDER_LISTS")]
    MaxNumOrderLists(Box<models::MaxNumOrderListsFilter>),
    #[serde(rename = "MAX_NUM_ORDER_AMENDS")]
    MaxNumOrderAmends(Box<models::MaxNumOrderAmendsFilter>),
}

impl Default for SymbolFilters {
    fn default() -> Self {
        Self::PriceFilter(Default::default())
    }
}
